export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';




export const ANNOUNCEMENTS_FAILED = 'ANNOUNCEMENTS_FAILED';
export const ADD_ANNOUNCEMENTS = 'ADD_ANNOUNCEMENTS';


export const RULES_FAILED = 'RULES_FAILED';
export const ADD_RULES = 'ADD_RULES';

 
export const CHALLENGES_FAILED = 'CHALLENGES_FAILED';
export const ADD_CHALLENGES = 'ADD_CHALLENGES'; 
export const ADD_UNIVERSITIES = 'ADD_UNIVERSITIES';

export const UNIVERSITIES_FAILED = 'UNIVERSITIES_FAILED';


